---
title: "Reinforcement Learning Reading Group #3 - Deep Q-learning (DQN)"
date: "2026-08-12"
categories: [rl, reading group, dqn, atari]
---

This article covers implementation notes for Deep Q-learning (DQN) on Atari as described in the [original nature paper](https://daiwk.github.io/assets/dqn.pdf). The goal is to write down the distinct components and design choices before we write any code. Ideally, writing the code for DQN should be a purely mechanical activity although realistically, a few choices are made much clearer during implementation e.g. code optimizations and some design choices.

::: {.hidden}
$$
\usepackage{amsmath}
\DeclareMathOperator*{\argmax}{arg\,max}
$$
:::


Recall that $Q^{\pi}(s,a)$ satisfies the Bellman equation:

$$Q^{\pi}(s,a) = \mathbb{E}_{s'\sim p(\cdot \mid s,a),a'\sim \pi(\cdot \mid s')} [ r(s,a,s') + \gamma Q^{\pi}(s',a')]$$

(including $r(s,a,s')$ in the expectation for environments with stochastic rewards).

Note that we can take the expectation over $a'$ "into" the linear sum i.e.

$$Q^{\pi}(s,a) = \mathbb{E}_{s'\sim p(\cdot \mid s,a)} [ r(s,a,s') + \gamma \mathbb{E}_{a'\sim \pi(\cdot \mid s')} Q^{\pi}(s',a')]$$

The optimal Q-value function satisfies:

$$Q^{*}(s,a) = \mathbb{E}_{s'\sim p(\cdot \mid s,a)} [ r(s,a,s') + \gamma \max_{a'} Q^{*}(s',a')]$$

We want to learn the optimal $Q^{*}(s,a)$. This quantity lets us pick optimal actions in any state $s$ by picking the action $a$ that maximizes $Q^{*}(s,a)$. In other words, knowing $Q^{*}$ defines a deterministic policy by $\pi(a\mid s) = \argmax_{a} Q^{*}(s,a)$ (as long as no two actions have exactly the same value for a given state). Note that the "max" is also an expectation under a deterministic policy. This can be seen as follows - the definition of expectation is:

$$\mathbb{E}_{a'\sim \pi} Q^{\pi}(s',a') = \Sigma_{a'} \pi(a'\mid s') Q^{\pi}(s',a')$$

Under a deterministic policy, one $a'$ has probability 1 while the rest have probabilities 0 i.e.

$$\mathbb{E}_{a'\sim \pi} Q^{\pi}(s',a') = \Sigma_{a'} \pi(a'\mid s') Q^{\pi}(s',a') = Q^{\pi}(s',\pi(s'))$$

For $Q^{*}$, this action is precisely the one that maximizes $Q^{*}(s,\cdot)$ which results in the Bellman optimality equation consisting of the $\max$.

These Bellman equations are constraints i.e. they require consistency between $Q^{*}/Q^{\pi}$ evaluated for various (s,a) pairs. There is one constraint/equation/consistency condition for each $(s,a)$ pair. We saw this explicitly in the tabular Q-learning [example](https://github.com/TreeinRandomForest/RL-intro/blob/main/QL/gridworld.py). Estimating $Q^{\pi}$ for each $(s,a)$ pair doesn't scale well as state-space and action-space sizes increase.

One can instead use a function approximator i.e. a model that approximates the $Q$ function:

$$Q^{*}(s,a) \approx Q_{\theta}(s,a)$$

where $\theta$ are the model's weights if one uses a linear model or a neural network.

In practice, the neural network takes the state $s$ (stacked image frames for Atari) as inputs and produces $\lvert\mathcal{A}\rvert$ (number of actions) Q-values as outputs.

Of course, we first need to train the neural network using some supervised objective i.e. by minimizing a loss of the form:

$$L = \mathbb{E}_{s,a}[Q_{\theta}(s,a) - y(s,a)]^2$$

i.e. a mean squared loss error with some target value $y(s,a)$ averaged over the distribution of state-action pairs $(s,a)$ seen in the data (replay buffer).

The Bellman equation tells us exactly what the target should be:

$$y(s,a) = \mathbb{E}_{s'\sim p(\cdot \mid s,a)} [ r(s,a,s') + \gamma \max_{a'} Q^{*}(s',a')]$$

The expectation is approximated by a single sample(!) as:

$$y(s,a) =  [r(s,a,s') + \gamma \max_{a'} Q^{*}(s',a')]$$

**Note**: In taking a single sample, we introduce higher variance into the $y(s,a)$ computation. As shown below (point 2), since we don't know $Q^{*}$, we use a noisy estimate, $Q^{(i-k)}$. The max chooses the $a'$ that maximizes this estimate which preferentially chooses actions that had a positive noise fluctuation. This will motivate Double DQN.


Computing $y(s,a)$ requires two components:

1. Tuples $(s,a,s',r)$ where $(s,a)$ label the state-action pair for which the constraint is being applied. $s'$ is the new state transitioned into for the single sample chosen to approximate the expectation value. $r$ is the observed reward since we usually don't know the reward function and can't compute $r(s,a,s')$ but can observe this value.

2. The target also needs $Q^{*}(s',a')$. But this is the quantity the neural network is trying to approximate. So the loss looks like $[Q_{\theta}(s,a) - y(s,a)]^2$ where both the predicted value and the target depend on $\theta$. While we'll explore this more quantitatively, this leads to unstable training since it's equivalent to supervised learning where the prediction and the label can both be changed by gradient descent. Instead, like in the tabular case, we use an iterative approach. 

The standard solution to (2) is to use the iterative nature of updates to $Q_{\theta}$. If the current model is $Q^{(i)}_{\theta}$, the target $y(s,a)$ is computed using a lagged model i.e. with a smaller $i$. For example, we might use the model every 10th iteration to compute the target. So, iterations $i=1$ to $i=9$ would use $Q^{(0)}$ to compute the target. Iterations $i=10$ to $i=19$ would use $Q^{(10)}$ to compute targets and so on. The target equation for iteration $i$ updates to:

$$y(s,a) = \mathbb{E}_{s'\sim p(\cdot \mid s,a)} [ r(s,a,s') + \gamma \max_{a'} Q^{(i-k)}(s',a')]$$



To summarize, we will approximate the Q-function with a neural network that predicts the optimal action-value $Q^{*}(s,a)$ for all actions in one forward pass i.e. there is one output per action for $Q_{\theta}$. The network is trained using the Bellman optimality condition to define a target. The target also requires $Q^{*}$ values and to avoid training instabilities, we use a lagged version of $Q_{\theta}$ to compute the target. The simplest choice for the state can be the current image frame (RGB or grayscale). To inject information about velocity and acceleration, we can stack consecutive frames.

As noted earlier, each loss term depends on one $(s,a,s',r)$ tuple. Each trajectory e.g. one instance of a game produces consecutive tuples 

$$(s_0, a_0, s_1, r_0, a_1, s_2, r_1, a_2, s_3, r_2, \ldots)$$

which can be decomposed into tuples:

$(s_0, a_0, s_1, r_0), (s_1, a_1, s_2, r_1), (s_2, a_2, s_3, r_2), \ldots$

These tuples are highly correlated which reduces the effective amount of information being collected. 

A subtle point: we are not approximating $Q^{\pi} \approx Q_{\theta}$. If we were, we would be on-policy i.e. we would need to collect tuples under the policy $\pi$, train $Q^{\theta}$ to approximate $Q^{\pi}$, improve the policy and then collect more tuples.

We are instead learning $Q^{*}$. This is independent of the data collection policy! It is by definition at least as good as any $Q^{\pi}$ i.e.

$$Q^{*}(s,a) \geq Q^{\pi}(s,a) \forall (s,a) \forall \pi$$

To learn $Q^{*}$, it doesn't matter what policy the data is collected under and we can mix various data collection policies together i.e. we can have a buffer/array of tuples collected under different policies.

**Fine-print 1**: The data collection policies are relevant for *coverage*. If a $(s,a)$ pair is never visited, we can't compute $Q^{*}(s,a)$. But as long as we keep visiting $(s,a)$ under any policy, we have some data that can be used to infer $Q^{*}(s,a)$.

**Fine-print 2**: For tabular Q-learning, fine-print 1 applies. For function approximation (e.g. using an NN to approximate $Q^{*}$, not only does fine-print 1 apply but the distribution of tuples is important during training because SGD will tradeoff approximation errors in seen data (reflected by the loss) with approximation errors in unseen data. More precisely, (a) there are no guarantees on unseen data - the approximation error might be large or small, and (b) even in seen tuples, under-represented tuples might have larger errors than well-represented tuples.

In general, the combination of function approximation (neural net in our case), bootstrapping (using $Q_{\theta}$ to define the target), and off-policy learning (buffer of tuples collected under different policies) can actually cause learning to become unstable where $Q_{\theta}(s,a) \rightarrow \infty$ in theory. In practice, these values can grow to unrealistic values but can also recover. This is known as the **deadly triad**. Small errors can compound rapidly e.g. see [paper](https://arxiv.org/pdf/1812.02648).

### Initial Environment

Do all initial experiments with **Pong**. This is especially helpful for debugging.

A good candidate for the next game is **Breakout** (see famous story about Woz and Jobs at Atari).

Run multiple seeds - at least 3-5 per experiment.

Use [Gymnasium](https://gymnasium.farama.org/v0.29.0/environments/atari/). [ale-py](https://pypi.org/project/ale-py/) has the games.

## Hardware

NVIDIA 3090/4090 should be enough since env is CPU-bound. Ensure you have enough vCPUs available.


### Ablations

The following is a non-exhaustive list of ablations:

**Replay Buffer Size**: The replay buffer breaks correlations between tuples. Tuples are added to the buffer and old ones are evicted to ensure the buffer doesn't exceed a maximum size. As the buffer is made smaller, we approach a more online sampling procedure where all tuples are from recent episodes and are therefore, more correlated.

Vary the buffer size e.g. 1, 100, 10000, 1M and observe the learning curves.

**Frame Stacking**: For various games, change the stacking size e.g. 1, 2, 4, 8 etc. to observe the impact including higher-derivative information (velocity, acceleration etc.)

**Target Network Freezing**: Use the current $Q$ network to calculate the target. A more comprehensive experiment would change the freezing frequency from 1 (no freezing) to 10k (paper's value) to a much higher value.

**$\varepsilon$**: 

During training, anneal $\varepsilon$ from high (e.g. 1.0 i.e. fully random policy) and linearly decay to small value (e.g. 0.05) over iterations.

During evaluation, fix $\varepsilon$ to small values (0.05) to avoid getting stuck in loops.

Can try various $\varepsilon$ decay schedules.


### Components

**Replay Buffer**:

TODO

- Fix typos
- MC (on-policy) vs optimality (off-policy)
