project:
  type: website

website:
  description: "Experiments with ML and Systems"
  site-url: https://treeinrandomforest.github.io/ml # you must change this appropriately for RSS feeds to work properly
  title: "Discovery"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: bluesky
        href: https://bsky.app/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

execute:
  freeze: auto

comments:
  giscus:
    repo: "TreeinRandomForest/ml"
    repo-id: "R_kgDOSTRqcg"
    category: "Announcements"
    category-id: "DIC_kwDOSTRqcs4C9Uu8"
    mapping: "pathname"
    reactions-enabled: true
    input-position: "bottom"
    theme: "light"
